name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labes) for Docker Web
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ secrets.DOCKER_USER }}/animemanga-web:2.1.0
        
    - name: Build the Docker image Web
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/animemanga-web:2.1.0, ${{ secrets.DOCKER_USER }}/animemanga-web:latest